
# ============== GENERAL ============== #

WIDTH = 1600
HEIGHT = 1000
FPS = 60

BACKGROUND_COLOR = (10, 10, 10)
PLAYER_COLOR = (255, 255, 255)


# ============== PLAYER ============== #

PLAYER_WIDTH = 40
PLAYER_HEIGHT = 20
PLAYER_SPEED = 300
PLAYER_ACCELERATION = 30000
PLAYER_MAX_SPEED = 300
PLAYER_DRAG = 0.85
PLAYER_LIVES = 3


# ============== BULLET ============== #

BULLET_WIDTH = 6
BULLET_HEIGHT = 16
BULLET_SPEED = 900


# ============== ENEMY ============== #

ENEMY_WIDTH = 40
ENEMY_HEIGHT = 30
ENEMY_SPEED = 150


# ============== SCOUT ============== #

SCOUT_WIDTH = 40
SCOUT_HEIGHT = 30

SCOUT_MAX_SPEED = 300
SCOUT_ACCELERATION = 500
SCOUT_DRAG = 0.95

SCOUT_COLOR = (180, 180, 180)


# ============== SHOOTER ============== #

SHOOTER_MAX_SPEED = 180
SHOOTER_ACCELERATION = 500
SHOOTER_DRAG = 0.90

SHOOTER_MIN_DISTANCE = 350
SHOOTER_MAX_DISTANCE = 550

ENEMY_BULLET_WIDTH = 6
ENEMY_BULLET_HEIGHT = 16
ENEMY_BULLET_SPEED = 500

SHOOTER_SHOOT_DELAY = 1.5


# ============== KAMIKAZE ============== #


KAMIKAZE_MAX_SPEED = 350
KAMIKAZE_ACCELERATION = 800
KAMIKAZE_DRAG = 0.92

KAMIKAZE_DETECTION_RADIUS = 700
KAMIKAZE_ATTACK_DISTANCE = 250

KAMIKAZE_WIDTH = 42
KAMIKAZE_HEIGHT = 42

KAMIKAZE_COLOR = (255, 80, 80)


# ============== DODGER ============== #

DODGER_MAX_SPEED = 260
DODGER_ACCELERATION = 900
DODGER_DRAG = 0.88

DODGER_DANGER_DISTANCE = 200
DODGER_PREDICTION_TIME = 1.5

DODGER_ATTACK_DISTANCE = 500
DODGER_SHOOT_DELAY = 1.8

# ============== TACTICAL ============== #

TACTICAL_MAX_SPEED = 220
TACTICAL_ACCELERATION = 500
TACTICAL_DRAG = 0.90

TACTICAL_MIN_DISTANCE = 400
TACTICAL_MAX_DISTANCE = 650

TACTICAL_SEPARATION_DISTANCE = 180
TACTICAL_SEPARATION_FORCE = 1.5

TACTICAL_SHOOT_DELAY = 2.0


# ============== BOSS 1 ============== #

BOSS_WIDTH = 140
BOSS_HEIGHT = 100

BOSS_MAX_HEALTH = 30

BOSS_MAX_SPEED = 180
BOSS_ACCELERATION = 400
BOSS_DRAG = 0.92

BOSS_MIN_DISTANCE = 450
BOSS_MAX_DISTANCE = 700

BOSS_SHOOT_DELAY = 1.0

BOSS_DASH_COOLDOWN = 5.0
BOSS_DASH_SPEED = 700
BOSS_DASH_DURATION = 0.35